{% set name = "miningpy" %}
{% set version = "0.6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7825c7933d80d76002630fca2f5a10da69cf118b6604a64ad089a0eb1b0b897a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - ezdxf >=0.13.1
    - numpy >=1.19.0
    - pandas >=1.0
    - python
    - pyvista >=0.32
    - pyvistaqt
    - pyqt
    - vtk >=9.1.0
    - matplotlib-base

test:
  imports:
    - miningpy

about:
  home: https://pypi.org/project/miningpy/
  summary: python tools for mining engineering
  license: MIT
  license_file: LICENSE
  dev_url: https://bitbucket.org/incitron/miningpy
  doc_url: https://miningpy.readthedocs.io

extra:
  recipe-maintainers:
    - iainfullelove
